SELECT *
FROM ecommerce_dataset;

-- Total Revenue
SELECT sum(total)
FROM ecommerce_dataset;
-- The total revenue generated from sales of products is 157193

-- Total Orders
SELECT count(distinct order_id)
FROM ecommerce_dataset;
-- There were 88 orders placed within the time period

-- Average Order value
SELECT ROUND(SUM(total)/count(DISTINCT order_id), 1)
FROM ecommerce_dataset;
-- About 1786.30 was generated per order placed.

-- Total Units Sold
SELECT sum(quantity)
FROM ecommerce_dataset;
-- 269 units of goods were sold between this time period

-- Average Items per order
SELECT SUM(QUANTITY)/count(distinct order_id)
FROM ecommerce_dataset;
-- There were about 3 items placed per order 

-- Monthly revenue trend
select monthname(order_date), sum(total)
FROM ecommerce_dataset
GROUP BY monthname(order_date), month(order_date)
ORDER BY month(order_date);
-- Revenue spiked in february with anbout 20% of total renevue actualized in the month.

-- Revenue Per category
SELECT category, ROUND(SUM(total)*100/(SELECT sum(total) FROM ecommerce_dataset),3)
FROM ecommerce_dataset
GROUP BY category;
-- Home products dominate the market with 40.5% being attributable to them.

-- Top 10 Best Selling Products(By Revenue)
SELECT product, sum(total)
FROM ecommerce_dataset
GROUP BY product
ORDER BY 2 DESC
LIMIT 10;
-- Blender was the highest selling product, generating the most revenue for the business while doubling the revenue generated by by the next best selling product.


-- Order Status Breakdown
SELECT `status`, count(order_id)*100/(select count(order_id) from ecommerce_dataset)
from ecommerce_dataset
group by `status`;
-- More than 1/4 of orders placed were returned, 22.7% has been shipped, same percentage applies to the number of goods being processed. While 15% were canclled with only about 1/10 of the goods delivered.

-- Revenue by Payment Method
SELECT payment_method, sum(total)
FROM ecommerce_dataset
GROUP BY Payment_Method;
-- Cash on delivery and bank transfer combined for 2/3 of the total revenue generated. while paypal and credit card took the rest. This is fairly common amongst E-Commerce sales.

-- Daily Order Volume
SELECT dayname(order_date), sum(total)
FROM ecommerce_dataset
GROUP BY dayname(order_date), weekday(order_date)
ORDER BY weekday(order_date);
-- There was an unusual dip and spike between Monday and Wednesday, tuesday being the day with the least recorded sales and wednesday being the day with the highest recorded sales. 
